_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: init_weights/mrcnn_r50_1x.pkl
  MASK_ON: True
  RESNETS:
    DEPTH: 50
    DEFORM_ON_PER_STAGE: [False, True, True, True] # on Res3, Res4, Res5
    DEFORM_MODULATED: False
INPUT:
  MIN_SIZE_TRAIN: (800,)
DATASETS:
  TRAIN: ("indiscapes_train_val_combined",)
  TEST: ("indiscapes_test",)
OUTPUT_DIR: "outputs/dconv"
SOLVER:
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 600
TEST:
  EVAL_PERIOD: 600
